src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post", orphanRemoval=true)
     * @ORM\OrderBy({"created_at" = "DESC"})
     */
    private $comments;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     */
    private $author;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $tags = [];

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        if( $this->getCreatedAt() === null ) {
            $this->setCreatedAt(new \DateTimeImmutable());
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getTags(): ?array
    {
        return $this->tags;
    }

    public function setTags(?array $tags): self
    {
        $this->tags = $tags;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\IsTrue;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Nadpis:'
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Obsah:'
            ])
            ->add('tags', TextType::class, [
                'label' => 'Tagy (oddelené medzerou)',

            ])
            ->add('image', FileType::class, [
                'label' => 'Obrázok',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '4096k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpeg'
                        ],
                        'mimeTypesMessage' => 'Nesprávny formát obrázka'
                    ])
                ]
            ])
        ;

        $builder->get('tags')
            ->addModelTransformer(new CallbackTransformer(
                function ($tagsAsArray) {
                    if($tagsAsArray === NULL OR empty($tagsAsArray))
                        return "";
                    return implode(' ', $tagsAsArray);
                },
                function ($tagsAsString) {
                    if($tagsAsString === "")
                        return [];
                    return explode(' ', $tagsAsString);
                }
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use App\Form\PostType;
use App\Repository\CommentRepository;
use App\Repository\PostRepository;
use Laminas\Tag\Cloud;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/post")
 */
class PostController extends AbstractController
{
    /**
     * @Route("/{id}/comment", name="post_comment", methods={"POST"})
     */
    public function comment(Post $post, Request $request): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->get('anonymous')->getData();
            if( !$data ) {
                $comment->setAuthor($this->getUser());
            }

            $comment->setPost( $post );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('post_show', ['id' => $post->getId()]);
    }

    /**
     * @Route("/", name="post_index", methods={"GET"})
     */
    public function index(PostRepository $postRepository): Response
    {
        return $this->render('post/index.html.twig', [
            'posts' => $postRepository->orderByCreatedAtDesc(),
            'cloud' => $this->getCloud($postRepository)
        ]);
    }

    /**
     * @Route("/new", name="post_new", methods={"GET","POST"})
     */
    public function new(Request $request, SluggerInterface $slugger): Response
    {
        if(!$this->getUser()) {
            return $this->redirectToRoute('post_index');
        }

        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setAuthor($this->getUser());

            $image = $form->get('image')->getData();

            if( $image ) {
                $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$image->guessExtension();

                try {
                    $image->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    dd($e);
                }

                $post->setImageFilename($newFilename);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('post/new.html.twig', [
            'post' => $post,
            'form' => $form
        ]);
    }

    /**
     * @Route("/{id}", name="post_show", methods={"GET"})
     */
    public function show(Post $post, Request $request): Response
    {
        $comment = new Comment();
        $comment_form = $this->createForm(CommentType::class, $comment);
        $comment_form->handleRequest($request);

        return $this->render('post/show.html.twig', [
            'post' => $post,
            'comment_form' => $comment_form->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="post_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Post $post, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image')->getData();

            if( $image ) {
                $originalFilename = pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$image->guessExtension();

                try {
                    $image->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    dd($e);
                }

                $post->setImageFilename($newFilename);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('post_show', ['id' => $post->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('post/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/tag/{tag}", name="post_tag")
     */
    public function tag($tag, PostRepository $postRepository) :Response
    {
        return $this->render('post/index.html.twig', [
            'posts' => $postRepository->getByTag($tag),
            'title' => 'Zoznam článkov s tagom ' . $tag,
            'all_url' => true,
            'cloud' => $this->getCloud($postRepository)
        ]);
    }

    public function getCloud(PostRepository $postRepository) {
        $tags = $postRepository->getTagsCount();
        $tagArray = [];

        foreach( $tags as $tag => $count) {
            $tagArray[] = [
                'title' => $tag,
                'weight' => $count,
                'params' => ['url' => $this->generateUrl('post_tag', ['tag' => $tag])]
            ];
        }

        return new Cloud([
            'tags' => $tagArray
        ]);
    }

    /**
     * @Route("/{id}", name="post_delete", methods={"POST"})
     */
    public function delete(Request $request, Post $post): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($post);
            $entityManager->flush();
        }

        return $this->redirectToRoute('post_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/post/_comment_form.html.twig
{{ form_start(comment_form, {'action': path('post_comment', {"id": post.id})}) }}
    {{ form_widget(comment_form) }}
    <button class="text-yellow-500">{{ button_label|default('Pridať') }}</button>
{{ form_end(comment_form) }}

templates/post/_delete_form.html.twig
{% if app.user and app.user.id is same as post.author.id %}
<form method="post" action="{{ path('post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="text-red-400 font-semibold text-lg">Zmazať článok</button>
</form>
{% endif %}

templates/post/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="text-yellow-500 font-bold text-lg">{{ button_label|default('Vytvoriť') }}</button>
{{ form_end(form) }}

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Upraviť Článok{% endblock %}

{% block body %}
    <h1 class="text-3xl font-semibold text-center">Upraviť Článok</h1>

    <div class="bg-gray-100 p-2">
        {{ include('post/_form.html.twig', {'button_label': 'Upraviť'}) }}
    </div>

    <a class="text-sm italic" href="{{ path('post_index') }}">Všetky články</a>

    {{ include('post/_delete_form.html.twig') }}
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title ?? 'Zoznam článkov' }}{% endblock %}

{% block body %}

    <h1 class="text-3xl font-semibold text-center">{{ title ?? 'Zoznam článkov' }}</h1>

    {% if all_url is defined and all_url %}
        <a class="text-sm" href="{{ path('post_index') }}">Späť na články</a>
        <br>
    {% endif %}

    {% if app.user %}
        <a class="text-green-300" href="{{ path('post_new') }}">Vytvoriť nový</a>
    {% endif %}

    {% for post in posts %}
        <a class="my-2 bg-gray-100 p-2 block relative" href="{{ path('post_show', {id: post.id}) }}">
            <div class="float-left">
                <img class="max-w-full" src="{{ asset('uploads/images/' ~ post.imageFilename) }}" alt="">
            </div>
            <div class="clear-both"></div>
            <div class="font-bold text-xl">
                {{ post.title }}
            </div>
            <div class="">
                {{ post.content[:100] }}
                {% if post.content|length > 100 %}
                    ... Čítať ďalej
                {% endif %}
            </div>
            <div class="text-xs">
                <span class="font-semibold">Autor: </span> {{ post.author.email }}
                <span class="font-semibold">Uverejnené: </span> {{ post.createdAt|date("H:m:s d M Y") }}
            </div>
        </a>
    {% else %}
        <div class="text-center">Žiadne články</div>
    {% endfor %}

    <div class="font-semibold text-center">
        Tag cloud
    </div>

    {{ cloud|raw }}
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nový článok{% endblock %}

{% block body %}
    <h1 class="text-3xl font-semibold text-center pb-3 pt-2">Nový článok</h1>

    <div class="bg-gray-100 p-2">
        {{ include('post/_form.html.twig') }}
    </div>

    <a class="text-sm italic" href="{{ path('post_index') }}">Všetky články</a>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ post.title }}{% endblock %}

{% block body %}
    <a class="text-sm" href="{{ path('post_index') }}">Späť na články</a>
    <h1 class="text-3xl font-semibold">{{ post.title }}</h1>

    {% if post.imageFilename %}
        <div class="">
            <img src="{{ asset('uploads/images/' ~ post.imageFilename) }}">
        </div>
    {% endif %}

    {% if post.tags %}
        <div class="font-semibold">Tagy:</div>
        <div class="py-2">
            {% for tag in post.tags %}
                <a href="{{ path('post_tag', {tag: tag}) }}" class="bg-gray-200 px-3 py-1 border border-gray-400 rounded mx-2 text-sm">
                    {{ tag }}
                </a>
            {% endfor %}
        </div>
    {% endif %}

    <div class="font-semibold">Autor: <span class="font-normal">{{ post.author.email }}</span></div>
    <div class="font-semibold">Uverejnené: <span class="font-normal">{{ post.createdAt|date("H:m:s d M Y") }}</span></div>

    <div class="text-xl font-medium">
        Obsah:
    </div>

    <div class="">
        {{ post.content }}
    </div>

    <a class="text-sm italic" href="{{ path('post_edit', {'id': post.id}) }}">Upraviť</a>


    <div class="w-full bg-gray-100 p-2">
        {{ include('post/_comment_form.html.twig') }}

        <div class="text-center py-3 text-2xl font-bold">
            Komentáre
        </div>

        {% for comment in post.comments %}
            <div class="border-b-2 border-gray-700 p-2">
                <div class="font-semibold">
                    {{ comment.author.email ?? "Anonym" }}
                </div>
                {{ comment.content }}
                <div class="text-xs font-light">
                    {{ comment.createdAt|date("H:m:s d M Y") }}
                </div>
            </div>
        {% else %}
            <div class="text-center">Žiadne komentáre</div>
        {% endfor %}
    </div>
{% endblock %}